
import = [
    # "~/.config/alacritty/themes/themes/coolnight.toml"
    "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.9 
blur = false 

option_as_alt = "Both"

[font]
# normal.family = "MesloLGS Nerd Font Mono"
# normal.family = "UbuntuMono Nerd Font"
# normal.family = "JetBrainsMono Nerd Font"
# normal.family = "RobotoMono Nerd Font"
# normal.family = "BlexMono Nerd Font"
normal.family = "Inconsolata Nerd Font"
# normal.family = "CascadiaCode Nerd Font"


size = 24
 
